version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Install phase started"

  pre_build:
    commands:
      - echo "Pre-build phase started"

  build:
    commands:
      - mkdir -p build
      - cp index.html build/

artifacts:
  files:
    - build/index.html
    - appspec.yml
    - scripts/**
